## {'up_age_vec': array([ 0.63300008,  1.00254344,  1.50906548,  1.50040911]),
##     'up_gender_vec': array([ 0.99869263,  1.07980477]),
##     'up_HC_offer_not_prev_att': 0.197,
##     'up_QRisk_vec': array([ 0.64004603,  0.98777947,  1.5542865 ,  1.8741683 ,  2.31162219]),
##     'up_AHT_eff_age55minus_SBP': -7.312418727360097,
##     'up_HC_aht_presc_Q20plus': 0.022637501962254048,
##     'up_HC_takeup': 0.488,
##     'up_Statins_eff_extra_female': 0.87,
##     'up_Weight_eff': -1.50734176401132,
##     'up_HC_include_bp_registers': False,
##     'up_HC_statins_presc_Q20plus': 0.13952075851815965,
##     'up_Statins_eff_HDL_female': 0.04679206135008977,
##     'up_AHT_eff_age55plus_DBP_female': -3.1834320880978786,
##     'up_AHT_eff_age55plus_SBP_female': -9.17374616717331,
##     'up_AHT_eff_age55plus_SBP_male': -7.5726882673638425,
##     'up_HC_offer_prev_att': 0.197,
##     'up_HC_include_CVD_registers': False,
##     'up_bp_diagnosis_fraction': 0.05,
##     'up_Statins_comp': 0.5036726874809458,
##     'up_HC_aht_presc_Q20minus': 0.014718518984658679,
##     'up_Weight_comp': 0.30083675530591525,
##     'up_Statins_eff_male': -1.2240288710032297,
##     'up_HC_include_diabetes_registers': False,
##     'up_HC_smoker_ref': 0.03741321360811903,
##     'up_AHT_eff_age55minus_DBP': -4.011668283081843,
##     'up_Smoking_eff': 0.15521265716762533,
##     'up_Statins_dropout_rate': 0.05,
##     'up_HC_takeup_noneligible': 0.04813336062269343,
##     'up_AHT_dropout_rate': 0.05,
##     'up_HC_statins_presc_Q20minus': 0.020250955214036817,
##     'up_Statins_eff_extra_male': 0.82,
##     'up_Statins_eff_female': -1.0966198203069308,
##     'up_CVD_diagnosis_fraction': 1.0,
##     'up_HC_age_limit': [40, 74],
##     'up_AHT_comp': 0.6616448784017878,
##     'up_Smoking_relapsing_rate': 0.35,
##     'up_HC_offered': 0.197,
##     'up_physically_active': 0.6,
##     'up_eth_vec': array([ 0.99970082, 1.02063108, 0.99056265,  0.86775503]),
##     'up_AHT_eff_age55plus_DBP_male': -3.0217952479856995,
##     'up_HC_takeup_rr_not_prev_att': 1.0,
##     'up_smoker_vec': array([ 1.00018187, 0.74182106]), 'up_SES_vec': array([ 0.9902975 ,  0.98067816,  0.99360265,  1.01951527, 1.2491194 ]),
##     'up_Statins_eff_HDL_male': 0.03385041475235148,
##     'up_HC_weight_ref': 0.2758317948940889,
##     'up_HC_takeup_rr_prev_att': 1.0}

parnames <- 
c(paste0('up_age_vec',1:4),
  paste0('up_gender_vec',1:2),
  'up_HC_offer_not_prev_att',
  paste0('up_QRisk_vec',1:5),
  'up_AHT_eff_age55minus_SBP',
  'up_HC_aht_presc_Q20plus',
  'up_HC_takeup',
  'up_Statins_eff_extra_female',
  'up_Weight_eff',
  'up_HC_include_bp_registers',
  'up_HC_statins_presc_Q20plus',
  'up_Statins_eff_HDL_female',
  'up_AHT_eff_age55plus_DBP_female',
  'up_AHT_eff_age55plus_SBP_female',
  'up_AHT_eff_age55plus_SBP_male',
  'up_HC_offer_prev_att',
  'up_HC_include_CVD_registers',
  'up_bp_diagnosis_fraction',
  'up_Statins_comp',
  'up_HC_aht_presc_Q20minus',
  'up_Weight_comp',
  'up_Statins_eff_male',
  'up_HC_include_diabetes_registers',
  'up_HC_smoker_ref',
  'up_AHT_eff_age55minus_DBP',
  'up_Smoking_eff',
  'up_Statins_dropout_rate',
  'up_HC_takeup_noneligible',
  'up_AHT_dropout_rate',
  'up_HC_statins_presc_Q20minus',
  'up_Statins_eff_extra_male',
  'up_Statins_eff_female',
  'up_CVD_diagnosis_fraction',
  paste0('up_HC_age_limit',1:2),
  'up_AHT_comp',
  'up_Smoking_relapsing_rate',
  'up_HC_offered',
  'up_physically_active',
  paste0('up_eth_vec',1:4),
  'up_AHT_eff_age55plus_DBP_male',
  'up_HC_takeup_rr_not_prev_att',
  paste0('up_smoker_vec',1:2),
  paste0('up_SES_vec',1:5),
  'up_Statins_eff_HDL_male',
  'up_HC_weight_ref',
  'up_HC_takeup_rr_prev_att')

fixedpars <- c("up_HC_offer_not_prev_att",
               "up_HC_takeup",
               "up_HC_include_bp_registers",
               "up_HC_offer_prev_att", "up_HC_include_CVD_registers", 
               "up_bp_diagnosis_fraction", "up_HC_include_diabetes_registers", 
               "up_CVD_diagnosis_fraction", "up_HC_age_limit1", "up_HC_age_limit2", 
               "up_Smoking_relapsing_rate", "up_HC_offered", "up_physically_active", 
               "up_HC_takeup_rr_not_prev_att", "up_HC_takeup_rr_prev_att")

## Some parameters in this array are fixed. 
## Some of the fixed ones surely have uncertainty in them. 
## and are learnable with more research: 

## 5% yearly dropout rates for statins and AHTs (done now) 
## extra statins effects beyond chol lowering  (done now) 
## yearly rate of relapsing after quitting smoking 
## yearly proportion of CVD / high BP events diagnosed 

parlabs <- rbind(c("Statins_dropout_rate1", "Dropout rate from statins per year", "3% - 7%", "Assumption"),
                 c("Statins_comp1", "Initial rate of adherence to statins", "40 - 60%", "Assumption"),
                 c("HC_takeup_noneligible1", "HC takeup rate of those noneligible", "2% - 8%", "Assumption"),
                 c("QRisk_log3", "HC uptake for QRisk 10-14.9 (relative to 5-9.9)", "1.32 - 1.36", "Data"),
                 c("HC_aht_presc_Q20minus1", "AHT prescription rate for QRisk < 20", "1.46 - 1.62", "Data"),
                 c("age_log3", "HC uptake for age 60-69 (relative to 50-59)", " 1.40 - 1.42", "Data"),
                 c("HC_weight_ref1", "Rate of referral to weight management for BMI 30+", "26.9% - 28.1%", "Data"),             
                 c("eth_log1", "Relative HC uptake for white", "", ""),             
                 c("QRisk_log5", "HC uptake for QRisk 20+ (relative to 5-9.9)", "1.68 - 1.74", "Data"),             
                 c("AHT_comp1", "Initial adherence rate to AHTs", "45% - 65%", "Assumption"),             
                 c("Statins_eff_male1", "Reduction in total cholesterol for men given statins", "1.19 - 1.26", "Data"),
                 c("eth_log2", "Relative HC uptake for South Asian ethnic groups (relative to white)", "1.00 - 1.05", "Data"),
                 c("SES_log4", "Relative HC uptake for 4th quintile of SES (relative to 1st=lowest)", "0.99 - 1.02", "Data"),
                 c("eq_lc1", "EQ5D utility decrement for lung cancer", "0.20 - 0.03", "Data"),
                 c("SES_log1", "Relative HC uptake for SES 1", "", ""),
                 c("eq_dem1", "EQ5D utility decrement for dementia", "", ""),
                 c("eq_ihd1", "EQ5D utility decrement for IHD", "", ""),
                 c("Smoking_eff1", "Proportion quit smoking by 1 year after cessation referral", "13.1% - 16.1%", "Data"),
                 c("HC_statins_presc_Q20minus1", "Statins prescription rate for QRisk < 20", "", ""),
                 c("AHT_dropout_rate1", "Annual drop out rate from antihypertensives", "", ""),
                 c("Weight_eff1", "Expected BMI change after weight management referral", "", ""),
                 c("smoker_log1", "Relative HC uptake for non-smokers", "", ""),
                 c("eq_2dis1", "EQ5D utility decrement for 2 concurrent diseases", "0.077 - 0.046", "Data"),
                 c("smoker_log2", "HC uptake for smokers (relative to non-smokers)", "0.76 - 0.78", "Data"),
                 c("eq_3dis1", "EQ5D utility decrement", "", ""),
                 c("HC_statins_presc_Q20plus1", "", "", ""),
                 c("gender_log2", "HC uptake for women (relative to men)", "", ""),
                 c("AHT_eff_age55plus_DBP_female1", "Reduction in DBP for women given AHTs aged 55+", "3.18 - 3.82", "Data"),
                 c("QRisk_log4", "HC uptake for QRisk 15-19.9 (relative to 5-9.9)", "1.49 - 1.55", "Data"),
                 c("eq_age1", "EQ5D utility decrement", "", ""),
                 c("AHT_eff_age55plus_SBP_female1", "Effect of AHTs on SBP for women age 55+", "", ""),
                 c("Statins_eff_HDL_male1", "Increase in HDL for men given statins", "0.028 - 0.052", "Data"),
                 c("eq_stroke1", "EQ5D utility decrement", "", ""),
                 c("Statins_logeff_extra_male10", "Effect of statins outside cholesterol for men", "", ""),
                 c("AHT_eff_age55plus_DBP_male1", "Reduction in DBP for men given AHTs aged 55+", "", ""),
                 c("age_log4", "Relative HC uptake for age 70-74", "", ""),
                 c("Statins_eff_HDL_female1", "Effect of statins on HDL for women", "", ""),
                 c("Statins_logeff_extra_female1", "Effect of statins outside cholesterol for women", "", ""),
                 c("SES_log2", "Relative HC uptake for ", "", ""),
                 c("AHT_eff_age55plus_SBP_male1", "Effect of AHTs on SBP for ages 55+", "", ""),
                 c("eq_4dis1", "EQ5D utility decrement", "", ""),
                 c("Weight_comp1", "", "", ""),
                 c("gender_log1", "Relative HC uptake for men", "", ""),
                 c("SES_log5", "Relative HC uptake for SES 5", "", ""),
                 c("eq_male1", "EQ5D utility decrement", "", ""),
                 c("AHT_eff_age55minus_SBP1", "Effect of AHTs on SBP for ages below 55", "", ""),
                 c("eth_log4", "Relative HC uptake for other ethnicity", "", ""),
                 c("AHT_eff_age55minus_DBP1", "Effect of AHTs on DBP for ages below 55", "", ""),
                 c("eq_poor1", "EQ5D utility decrement", "", ""),
                 c("age_log1", "Relative HC uptake for age 40-49", "", ""),
                 c("eth_log3", "Relative HC uptake for Black", "", ""),
                 c("QRisk_log2", "Relative HC uptake for QRisk 5-9.9", "", ""),
                 c("HC_smoker_ref1", "Referral rates of smokers to cessation", "", ""),
                 c("QRisk_log1", "Relative HC uptake for QRisk < 5", "", ""),
                 c("SES_log3", "Relative HC uptake for ", "", ""),
                 c("age_log2", "Relative HC uptake for age 50-59", "", ""),
                 c("HC_aht_presc_Q20plus1", "AHT prescription rate for QRisk 20+", "", ""),
                 c("Statins_eff_female1", "Reduction in total cholesterol for women with statins", "1.10 - 1.23", "Data"),
                 c("QRisk_extra_logrr1", "", "", ""))
parlabs <- as.data.frame(parlabs, stringsAsFactors=FALSE)
names(parlabs) <- c("var","name","val","source")
